// Code generated by MockGen. DO NOT EDIT.
// Source: internal/execution/execution.go

// Package execution is a generated GoMock package.
package execution

import (
	gomock "github.com/golang/mock/gomock"
)

// MockExecution is a mock of Execution interface
type MockExecution struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionMockRecorder
}

// MockExecutionMockRecorder is the mock recorder for MockExecution
type MockExecutionMockRecorder struct {
	mock *MockExecution
}

// NewMockExecution creates a new mock instance
func NewMockExecution(ctrl *gomock.Controller) *MockExecution {
	mock := &MockExecution{ctrl: ctrl}
	mock.recorder = &MockExecutionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExecution) EXPECT() *MockExecutionMockRecorder {
	return m.recorder
}
