// Code generated by fastssz. DO NOT EDIT.
// Hash: f038da96ba0d658b4d2b7f6ab3b07a46861892f02d6dfd95a206d2d0ff0cdf7a
package primitives

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Block object
func (b *Block) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the Block object to a target array
func (b *Block) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(684)

	// Field (0) 'Header'
	if b.Header == nil {
		b.Header = new(BlockHeader)
	}
	if dst, err = b.Header.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, b.Signature[:]...)

	// Field (2) 'RandaoSignature'
	dst = append(dst, b.RandaoSignature[:]...)

	// Offset (3) 'Votes'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Votes); ii++ {
		offset += 4
		offset += b.Votes[ii].SizeSSZ()
	}

	// Offset (4) 'Deposits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Deposits) * 308

	// Offset (5) 'Exits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Exits) * 192

	// Offset (6) 'PartialExit'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PartialExit) * 200

	// Offset (7) 'Txs'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Txs) * 188

	// Offset (8) 'ProposerSlashings'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.ProposerSlashings) * 1160

	// Offset (9) 'VoteSlashings'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.VoteSlashings); ii++ {
		offset += 4
		offset += b.VoteSlashings[ii].SizeSSZ()
	}

	// Offset (10) 'RANDAOSlashings'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.RANDAOSlashings) * 152

	// Field (3) 'Votes'
	if len(b.Votes) > 16 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(b.Votes)
		for ii := 0; ii < len(b.Votes); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Votes[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Votes); ii++ {
		if dst, err = b.Votes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (4) 'Deposits'
	if len(b.Deposits) > 32 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.Deposits); ii++ {
		if dst, err = b.Deposits[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (5) 'Exits'
	if len(b.Exits) > 32 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.Exits); ii++ {
		if dst, err = b.Exits[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (6) 'PartialExit'
	if len(b.PartialExit) > 32 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.PartialExit); ii++ {
		if dst, err = b.PartialExit[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (7) 'Txs'
	if len(b.Txs) > 5000 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.Txs); ii++ {
		if dst, err = b.Txs[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (8) 'ProposerSlashings'
	if len(b.ProposerSlashings) > 2 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.ProposerSlashings); ii++ {
		if dst, err = b.ProposerSlashings[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (9) 'VoteSlashings'
	if len(b.VoteSlashings) > 5 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(b.VoteSlashings)
		for ii := 0; ii < len(b.VoteSlashings); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.VoteSlashings[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.VoteSlashings); ii++ {
		if dst, err = b.VoteSlashings[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (10) 'RANDAOSlashings'
	if len(b.RANDAOSlashings) > 20 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(b.RANDAOSlashings); ii++ {
		if dst, err = b.RANDAOSlashings[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Block object
func (b *Block) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 684 {
		return ssz.ErrSize
	}

	tail := buf
	var o3, o4, o5, o6, o7, o8, o9, o10 uint64

	// Field (0) 'Header'
	if b.Header == nil {
		b.Header = new(BlockHeader)
	}
	if err = b.Header.UnmarshalSSZ(buf[0:460]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(b.Signature[:], buf[460:556])

	// Field (2) 'RandaoSignature'
	copy(b.RandaoSignature[:], buf[556:652])

	// Offset (3) 'Votes'
	if o3 = ssz.ReadOffset(buf[652:656]); o3 > size {
		return ssz.ErrOffset
	}

	if o3 < 684 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (4) 'Deposits'
	if o4 = ssz.ReadOffset(buf[656:660]); o4 > size || o3 > o4 {
		return ssz.ErrOffset
	}

	// Offset (5) 'Exits'
	if o5 = ssz.ReadOffset(buf[660:664]); o5 > size || o4 > o5 {
		return ssz.ErrOffset
	}

	// Offset (6) 'PartialExit'
	if o6 = ssz.ReadOffset(buf[664:668]); o6 > size || o5 > o6 {
		return ssz.ErrOffset
	}

	// Offset (7) 'Txs'
	if o7 = ssz.ReadOffset(buf[668:672]); o7 > size || o6 > o7 {
		return ssz.ErrOffset
	}

	// Offset (8) 'ProposerSlashings'
	if o8 = ssz.ReadOffset(buf[672:676]); o8 > size || o7 > o8 {
		return ssz.ErrOffset
	}

	// Offset (9) 'VoteSlashings'
	if o9 = ssz.ReadOffset(buf[676:680]); o9 > size || o8 > o9 {
		return ssz.ErrOffset
	}

	// Offset (10) 'RANDAOSlashings'
	if o10 = ssz.ReadOffset(buf[680:684]); o10 > size || o9 > o10 {
		return ssz.ErrOffset
	}

	// Field (3) 'Votes'
	{
		buf = tail[o3:o4]
		num, err := ssz.DecodeDynamicLength(buf, 16)
		if err != nil {
			return err
		}
		b.Votes = make([]*MultiValidatorVote, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Votes[indx] == nil {
				b.Votes[indx] = new(MultiValidatorVote)
			}
			if err = b.Votes[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (4) 'Deposits'
	{
		buf = tail[o4:o5]
		num, err := ssz.DivideInt2(len(buf), 308, 32)
		if err != nil {
			return err
		}
		b.Deposits = make([]*Deposit, num)
		for ii := 0; ii < num; ii++ {
			if b.Deposits[ii] == nil {
				b.Deposits[ii] = new(Deposit)
			}
			if err = b.Deposits[ii].UnmarshalSSZ(buf[ii*308 : (ii+1)*308]); err != nil {
				return err
			}
		}
	}

	// Field (5) 'Exits'
	{
		buf = tail[o5:o6]
		num, err := ssz.DivideInt2(len(buf), 192, 32)
		if err != nil {
			return err
		}
		b.Exits = make([]*Exit, num)
		for ii := 0; ii < num; ii++ {
			if b.Exits[ii] == nil {
				b.Exits[ii] = new(Exit)
			}
			if err = b.Exits[ii].UnmarshalSSZ(buf[ii*192 : (ii+1)*192]); err != nil {
				return err
			}
		}
	}

	// Field (6) 'PartialExit'
	{
		buf = tail[o6:o7]
		num, err := ssz.DivideInt2(len(buf), 200, 32)
		if err != nil {
			return err
		}
		b.PartialExit = make([]*PartialExit, num)
		for ii := 0; ii < num; ii++ {
			if b.PartialExit[ii] == nil {
				b.PartialExit[ii] = new(PartialExit)
			}
			if err = b.PartialExit[ii].UnmarshalSSZ(buf[ii*200 : (ii+1)*200]); err != nil {
				return err
			}
		}
	}

	// Field (7) 'Txs'
	{
		buf = tail[o7:o8]
		num, err := ssz.DivideInt2(len(buf), 188, 5000)
		if err != nil {
			return err
		}
		b.Txs = make([]*Tx, num)
		for ii := 0; ii < num; ii++ {
			if b.Txs[ii] == nil {
				b.Txs[ii] = new(Tx)
			}
			if err = b.Txs[ii].UnmarshalSSZ(buf[ii*188 : (ii+1)*188]); err != nil {
				return err
			}
		}
	}

	// Field (8) 'ProposerSlashings'
	{
		buf = tail[o8:o9]
		num, err := ssz.DivideInt2(len(buf), 1160, 2)
		if err != nil {
			return err
		}
		b.ProposerSlashings = make([]*ProposerSlashing, num)
		for ii := 0; ii < num; ii++ {
			if b.ProposerSlashings[ii] == nil {
				b.ProposerSlashings[ii] = new(ProposerSlashing)
			}
			if err = b.ProposerSlashings[ii].UnmarshalSSZ(buf[ii*1160 : (ii+1)*1160]); err != nil {
				return err
			}
		}
	}

	// Field (9) 'VoteSlashings'
	{
		buf = tail[o9:o10]
		num, err := ssz.DecodeDynamicLength(buf, 5)
		if err != nil {
			return err
		}
		b.VoteSlashings = make([]*VoteSlashing, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.VoteSlashings[indx] == nil {
				b.VoteSlashings[indx] = new(VoteSlashing)
			}
			if err = b.VoteSlashings[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (10) 'RANDAOSlashings'
	{
		buf = tail[o10:]
		num, err := ssz.DivideInt2(len(buf), 152, 20)
		if err != nil {
			return err
		}
		b.RANDAOSlashings = make([]*RANDAOSlashing, num)
		for ii := 0; ii < num; ii++ {
			if b.RANDAOSlashings[ii] == nil {
				b.RANDAOSlashings[ii] = new(RANDAOSlashing)
			}
			if err = b.RANDAOSlashings[ii].UnmarshalSSZ(buf[ii*152 : (ii+1)*152]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Block object
func (b *Block) SizeSSZ() (size int) {
	size = 684

	// Field (3) 'Votes'
	for ii := 0; ii < len(b.Votes); ii++ {
		size += 4
		size += b.Votes[ii].SizeSSZ()
	}

	// Field (4) 'Deposits'
	size += len(b.Deposits) * 308

	// Field (5) 'Exits'
	size += len(b.Exits) * 192

	// Field (6) 'PartialExit'
	size += len(b.PartialExit) * 200

	// Field (7) 'Txs'
	size += len(b.Txs) * 188

	// Field (8) 'ProposerSlashings'
	size += len(b.ProposerSlashings) * 1160

	// Field (9) 'VoteSlashings'
	for ii := 0; ii < len(b.VoteSlashings); ii++ {
		size += 4
		size += b.VoteSlashings[ii].SizeSSZ()
	}

	// Field (10) 'RANDAOSlashings'
	size += len(b.RANDAOSlashings) * 152

	return
}

// HashTreeRoot ssz hashes the Block object
func (b *Block) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the Block object with a hasher
func (b *Block) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Header'
	if err = b.Header.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(b.Signature[:])

	// Field (2) 'RandaoSignature'
	hh.PutBytes(b.RandaoSignature[:])

	// Field (3) 'Votes'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Votes))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.Votes[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	// Field (4) 'Deposits'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Deposits))
		if num > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.Deposits[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 32)
	}

	// Field (5) 'Exits'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Exits))
		if num > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.Exits[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 32)
	}

	// Field (6) 'PartialExit'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PartialExit))
		if num > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.PartialExit[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 32)
	}

	// Field (7) 'Txs'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Txs))
		if num > 5000 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.Txs[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 5000)
	}

	// Field (8) 'ProposerSlashings'
	{
		subIndx := hh.Index()
		num := uint64(len(b.ProposerSlashings))
		if num > 2 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.ProposerSlashings[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 2)
	}

	// Field (9) 'VoteSlashings'
	{
		subIndx := hh.Index()
		num := uint64(len(b.VoteSlashings))
		if num > 5 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.VoteSlashings[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 5)
	}

	// Field (10) 'RANDAOSlashings'
	{
		subIndx := hh.Index()
		num := uint64(len(b.RANDAOSlashings))
		if num > 20 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for i := uint64(0); i < num; i++ {
			if err = b.RANDAOSlashings[i].HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 20)
	}

	hh.Merkleize(indx)
	return
}
