// Code generated by fastssz. DO NOT EDIT.
// Hash: c02cdefb0be72cdd4edfdc0cbed048bb58baf99cfa86cefab5fbbc23bc9ebf5f
package primitives

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BlockHeader object
func (b *BlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlockHeader object to a target array
func (b *BlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Version'
	dst = ssz.MarshalUint64(dst, b.Version)

	// Field (1) 'Timestamp'
	dst = ssz.MarshalUint64(dst, b.Timestamp)

	// Field (2) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (3) 'PrevBlockHash'
	dst = append(dst, b.PrevBlockHash[:]...)

	// Field (4) 'FeeAddress'
	dst = append(dst, b.FeeAddress[:]...)

	// Field (5) 'VoteMerkleRoot'
	dst = append(dst, b.VoteMerkleRoot[:]...)

	// Field (6) 'DepositMerkleRoot'
	dst = append(dst, b.DepositMerkleRoot[:]...)

	// Field (7) 'ExitMerkleRoot'
	dst = append(dst, b.ExitMerkleRoot[:]...)

	// Field (8) 'PartialExitMerkleRoot'
	dst = append(dst, b.PartialExitMerkleRoot[:]...)

	// Field (9) 'CoinProofsMerkleRoot'
	dst = append(dst, b.CoinProofsMerkleRoot[:]...)

	// Field (10) 'ExecutionsMerkleRoot'
	dst = append(dst, b.ExecutionsMerkleRoot[:]...)

	// Field (11) 'TxsMerkleRoot'
	dst = append(dst, b.TxsMerkleRoot[:]...)

	// Field (12) 'ProposerSlashingMerkleRoot'
	dst = append(dst, b.ProposerSlashingMerkleRoot[:]...)

	// Field (13) 'VoteSlashingMerkleRoot'
	dst = append(dst, b.VoteSlashingMerkleRoot[:]...)

	// Field (14) 'RANDAOSlashingMerkleRoot'
	dst = append(dst, b.RANDAOSlashingMerkleRoot[:]...)

	// Field (15) 'GovernanceVotesMerkleRoot'
	dst = append(dst, b.GovernanceVotesMerkleRoot[:]...)

	// Field (16) 'MultiSignatureTxsMerkleRoot'
	dst = append(dst, b.MultiSignatureTxsMerkleRoot[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BlockHeader object
func (b *BlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 460 {
		return ssz.ErrSize
	}

	// Field (0) 'Version'
	b.Version = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Timestamp'
	b.Timestamp = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[16:24])

	// Field (3) 'PrevBlockHash'
	copy(b.PrevBlockHash[:], buf[24:56])

	// Field (4) 'FeeAddress'
	copy(b.FeeAddress[:], buf[56:76])

	// Field (5) 'VoteMerkleRoot'
	copy(b.VoteMerkleRoot[:], buf[76:108])

	// Field (6) 'DepositMerkleRoot'
	copy(b.DepositMerkleRoot[:], buf[108:140])

	// Field (7) 'ExitMerkleRoot'
	copy(b.ExitMerkleRoot[:], buf[140:172])

	// Field (8) 'PartialExitMerkleRoot'
	copy(b.PartialExitMerkleRoot[:], buf[172:204])

	// Field (9) 'CoinProofsMerkleRoot'
	copy(b.CoinProofsMerkleRoot[:], buf[204:236])

	// Field (10) 'ExecutionsMerkleRoot'
	copy(b.ExecutionsMerkleRoot[:], buf[236:268])

	// Field (11) 'TxsMerkleRoot'
	copy(b.TxsMerkleRoot[:], buf[268:300])

	// Field (12) 'ProposerSlashingMerkleRoot'
	copy(b.ProposerSlashingMerkleRoot[:], buf[300:332])

	// Field (13) 'VoteSlashingMerkleRoot'
	copy(b.VoteSlashingMerkleRoot[:], buf[332:364])

	// Field (14) 'RANDAOSlashingMerkleRoot'
	copy(b.RANDAOSlashingMerkleRoot[:], buf[364:396])

	// Field (15) 'GovernanceVotesMerkleRoot'
	copy(b.GovernanceVotesMerkleRoot[:], buf[396:428])

	// Field (16) 'MultiSignatureTxsMerkleRoot'
	copy(b.MultiSignatureTxsMerkleRoot[:], buf[428:460])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlockHeader object
func (b *BlockHeader) SizeSSZ() (size int) {
	size = 460
	return
}

// HashTreeRoot ssz hashes the BlockHeader object
func (b *BlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlockHeader object with a hasher
func (b *BlockHeader) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Version'
	hh.PutUint64(b.Version)

	// Field (1) 'Timestamp'
	hh.PutUint64(b.Timestamp)

	// Field (2) 'Slot'
	hh.PutUint64(b.Slot)

	// Field (3) 'PrevBlockHash'
	hh.PutBytes(b.PrevBlockHash[:])

	// Field (4) 'FeeAddress'
	hh.PutBytes(b.FeeAddress[:])

	// Field (5) 'VoteMerkleRoot'
	hh.PutBytes(b.VoteMerkleRoot[:])

	// Field (6) 'DepositMerkleRoot'
	hh.PutBytes(b.DepositMerkleRoot[:])

	// Field (7) 'ExitMerkleRoot'
	hh.PutBytes(b.ExitMerkleRoot[:])

	// Field (8) 'PartialExitMerkleRoot'
	hh.PutBytes(b.PartialExitMerkleRoot[:])

	// Field (9) 'CoinProofsMerkleRoot'
	hh.PutBytes(b.CoinProofsMerkleRoot[:])

	// Field (10) 'ExecutionsMerkleRoot'
	hh.PutBytes(b.ExecutionsMerkleRoot[:])

	// Field (11) 'TxsMerkleRoot'
	hh.PutBytes(b.TxsMerkleRoot[:])

	// Field (12) 'ProposerSlashingMerkleRoot'
	hh.PutBytes(b.ProposerSlashingMerkleRoot[:])

	// Field (13) 'VoteSlashingMerkleRoot'
	hh.PutBytes(b.VoteSlashingMerkleRoot[:])

	// Field (14) 'RANDAOSlashingMerkleRoot'
	hh.PutBytes(b.RANDAOSlashingMerkleRoot[:])

	// Field (15) 'GovernanceVotesMerkleRoot'
	hh.PutBytes(b.GovernanceVotesMerkleRoot[:])

	// Field (16) 'MultiSignatureTxsMerkleRoot'
	hh.PutBytes(b.MultiSignatureTxsMerkleRoot[:])

	hh.Merkleize(indx)
	return
}
