// Code generated by MockGen. DO NOT EDIT.
// Source: internal/hostnode/syncprotocol.go

// Package hostnode is a generated GoMock package.
package hostnode

import (
	gomock "github.com/golang/mock/gomock"
	network "github.com/libp2p/go-libp2p-core/network"
	multiaddr "github.com/multiformats/go-multiaddr"
	reflect "reflect"
)

// MockSyncProtocol is a mock of SyncProtocol interface
type MockSyncProtocol struct {
	ctrl     *gomock.Controller
	recorder *MockSyncProtocolMockRecorder
}

// MockSyncProtocolMockRecorder is the mock recorder for MockSyncProtocol
type MockSyncProtocolMockRecorder struct {
	mock *MockSyncProtocol
}

// NewMockSyncProtocol creates a new mock instance
func NewMockSyncProtocol(ctrl *gomock.Controller) *MockSyncProtocol {
	mock := &MockSyncProtocol{ctrl: ctrl}
	mock.recorder = &MockSyncProtocolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSyncProtocol) EXPECT() *MockSyncProtocolMockRecorder {
	return m.recorder
}

// Notify mocks base method
func (m *MockSyncProtocol) Notify(notifee SyncNotifee) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", notifee)
}

// Notify indicates an expected call of Notify
func (mr *MockSyncProtocolMockRecorder) Notify(notifee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockSyncProtocol)(nil).Notify), notifee)
}

// Listen mocks base method
func (m *MockSyncProtocol) Listen(arg0 network.Network, arg1 multiaddr.Multiaddr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Listen", arg0, arg1)
}

// Listen indicates an expected call of Listen
func (mr *MockSyncProtocolMockRecorder) Listen(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockSyncProtocol)(nil).Listen), arg0, arg1)
}

// ListenClose mocks base method
func (m *MockSyncProtocol) ListenClose(arg0 network.Network, arg1 multiaddr.Multiaddr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenClose", arg0, arg1)
}

// ListenClose indicates an expected call of ListenClose
func (mr *MockSyncProtocolMockRecorder) ListenClose(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenClose", reflect.TypeOf((*MockSyncProtocol)(nil).ListenClose), arg0, arg1)
}

// Connected mocks base method
func (m *MockSyncProtocol) Connected(net network.Network, conn network.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Connected", net, conn)
}

// Connected indicates an expected call of Connected
func (mr *MockSyncProtocolMockRecorder) Connected(net, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockSyncProtocol)(nil).Connected), net, conn)
}

// Disconnected mocks base method
func (m *MockSyncProtocol) Disconnected(net network.Network, conn network.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disconnected", net, conn)
}

// Disconnected indicates an expected call of Disconnected
func (mr *MockSyncProtocolMockRecorder) Disconnected(net, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnected", reflect.TypeOf((*MockSyncProtocol)(nil).Disconnected), net, conn)
}

// OpenedStream mocks base method
func (m *MockSyncProtocol) OpenedStream(net network.Network, stream network.Stream) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OpenedStream", net, stream)
}

// OpenedStream indicates an expected call of OpenedStream
func (mr *MockSyncProtocolMockRecorder) OpenedStream(net, stream interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenedStream", reflect.TypeOf((*MockSyncProtocol)(nil).OpenedStream), net, stream)
}

// ClosedStream mocks base method
func (m *MockSyncProtocol) ClosedStream(arg0 network.Network, arg1 network.Stream) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClosedStream", arg0, arg1)
}

// ClosedStream indicates an expected call of ClosedStream
func (mr *MockSyncProtocolMockRecorder) ClosedStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosedStream", reflect.TypeOf((*MockSyncProtocol)(nil).ClosedStream), arg0, arg1)
}

// Syncing mocks base method
func (m *MockSyncProtocol) Syncing() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Syncing")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Syncing indicates an expected call of Syncing
func (mr *MockSyncProtocolMockRecorder) Syncing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Syncing", reflect.TypeOf((*MockSyncProtocol)(nil).Syncing))
}

// MockSyncNotifee is a mock of SyncNotifee interface
type MockSyncNotifee struct {
	ctrl     *gomock.Controller
	recorder *MockSyncNotifeeMockRecorder
}

// MockSyncNotifeeMockRecorder is the mock recorder for MockSyncNotifee
type MockSyncNotifeeMockRecorder struct {
	mock *MockSyncNotifee
}

// NewMockSyncNotifee creates a new mock instance
func NewMockSyncNotifee(ctrl *gomock.Controller) *MockSyncNotifee {
	mock := &MockSyncNotifee{ctrl: ctrl}
	mock.recorder = &MockSyncNotifeeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSyncNotifee) EXPECT() *MockSyncNotifeeMockRecorder {
	return m.recorder
}
