// Code generated by fastssz. DO NOT EDIT.
package p2p

import (
	ssz "github.com/ferranbt/fastssz"
	"github.com/olympus-protocol/ogen/pkg/primitives"
)

// MarshalSSZ ssz marshals the MsgDeposit object
func (m *MsgDeposit) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(m)
}

// MarshalSSZTo ssz marshals the MsgDeposit object to a target array
func (m *MsgDeposit) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Data'
	if m.Data == nil {
		m.Data = new(primitives.Deposit)
	}
	if dst, err = m.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the MsgDeposit object
func (m *MsgDeposit) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 308 {
		return ssz.ErrSize
	}

	// Field (0) 'Data'
	if m.Data == nil {
		m.Data = new(primitives.Deposit)
	}
	if err = m.Data.UnmarshalSSZ(buf[0:308]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the MsgDeposit object
func (m *MsgDeposit) SizeSSZ() (size int) {
	size = 308
	return
}

// HashTreeRoot ssz hashes the MsgDeposit object
func (m *MsgDeposit) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(m)
}

// HashTreeRootWith ssz hashes the MsgDeposit object with a hasher
func (m *MsgDeposit) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	if err = m.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}
