// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: chainrpc/proto/validators.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetValidatorsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validators []*ValidatorInfo `protobuf:"bytes,1,rep,name=Validators,proto3" json:"Validators,omitempty"`
}

func (x *GetValidatorsListResponse) Reset() {
	*x = GetValidatorsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValidatorsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidatorsListResponse) ProtoMessage() {}

func (x *GetValidatorsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidatorsListResponse.ProtoReflect.Descriptor instead.
func (*GetValidatorsListResponse) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{0}
}

func (x *GetValidatorsListResponse) GetValidators() []*ValidatorInfo {
	if x != nil {
		return x.Validators
	}
	return nil
}

type ValidatorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Balance   string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ValidatorInfo) Reset() {
	*x = ValidatorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorInfo) ProtoMessage() {}

func (x *ValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorInfo.ProtoReflect.Descriptor instead.
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ValidatorInfo) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *ValidatorInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GenerateValidatorKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GenerateValidatorKeyResponse) Reset() {
	*x = GenerateValidatorKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateValidatorKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateValidatorKeyResponse) ProtoMessage() {}

func (x *GenerateValidatorKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateValidatorKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateValidatorKeyResponse) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateValidatorKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExitValidatorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *ExitValidatorInfo) Reset() {
	*x = ExitValidatorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitValidatorInfo) ProtoMessage() {}

func (x *ExitValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitValidatorInfo.ProtoReflect.Descriptor instead.
func (*ExitValidatorInfo) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{3}
}

func (x *ExitValidatorInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ExitValidatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ExitValidatorResponse) Reset() {
	*x = ExitValidatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitValidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitValidatorResponse) ProtoMessage() {}

func (x *ExitValidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitValidatorResponse.ProtoReflect.Descriptor instead.
func (*ExitValidatorResponse) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{4}
}

func (x *ExitValidatorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartValidatorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *StartValidatorInfo) Reset() {
	*x = StartValidatorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartValidatorInfo) ProtoMessage() {}

func (x *StartValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartValidatorInfo.ProtoReflect.Descriptor instead.
func (*StartValidatorInfo) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{5}
}

func (x *StartValidatorInfo) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type StartValidatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *StartValidatorResponse) Reset() {
	*x = StartValidatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainrpc_proto_validators_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartValidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartValidatorResponse) ProtoMessage() {}

func (x *StartValidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrpc_proto_validators_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartValidatorResponse.ProtoReflect.Descriptor instead.
func (*StartValidatorResponse) Descriptor() ([]byte, []int) {
	return file_chainrpc_proto_validators_proto_rawDescGZIP(), []int{6}
}

func (x *StartValidatorResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_chainrpc_proto_validators_proto protoreflect.FileDescriptor

var file_chainrpc_proto_validators_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x5f, 0x0a, 0x0d, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x1c,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x31,
	0x0a, 0x11, 0x45, 0x78, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x31, 0x0a, 0x15, 0x45, 0x78, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x34, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x36, 0x0a, 0x16, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x32, 0x89, 0x02, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x12, 0x39, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a,
	0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x14,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x4b, 0x65, 0x79, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0d, 0x45, 0x78, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x2e, 0x45, 0x78, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x13,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x17, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x79,
	0x6d, 0x70, 0x75, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chainrpc_proto_validators_proto_rawDescOnce sync.Once
	file_chainrpc_proto_validators_proto_rawDescData = file_chainrpc_proto_validators_proto_rawDesc
)

func file_chainrpc_proto_validators_proto_rawDescGZIP() []byte {
	file_chainrpc_proto_validators_proto_rawDescOnce.Do(func() {
		file_chainrpc_proto_validators_proto_rawDescData = protoimpl.X.CompressGZIP(file_chainrpc_proto_validators_proto_rawDescData)
	})
	return file_chainrpc_proto_validators_proto_rawDescData
}

var file_chainrpc_proto_validators_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chainrpc_proto_validators_proto_goTypes = []interface{}{
	(*GetValidatorsListResponse)(nil),    // 0: GetValidatorsListResponse
	(*ValidatorInfo)(nil),                // 1: ValidatorInfo
	(*GenerateValidatorKeyResponse)(nil), // 2: GenerateValidatorKeyResponse
	(*ExitValidatorInfo)(nil),            // 3: ExitValidatorInfo
	(*ExitValidatorResponse)(nil),        // 4: ExitValidatorResponse
	(*StartValidatorInfo)(nil),           // 5: StartValidatorInfo
	(*StartValidatorResponse)(nil),       // 6: StartValidatorResponse
	(*Empty)(nil),                        // 7: Empty
}
var file_chainrpc_proto_validators_proto_depIdxs = []int32{
	1, // 0: GetValidatorsListResponse.Validators:type_name -> ValidatorInfo
	7, // 1: Validators.GetValidatorsList:input_type -> Empty
	7, // 2: Validators.GenerateValidatorKey:input_type -> Empty
	3, // 3: Validators.ExitValidator:input_type -> ExitValidatorInfo
	5, // 4: Validators.StartValidator:input_type -> StartValidatorInfo
	0, // 5: Validators.GetValidatorsList:output_type -> GetValidatorsListResponse
	2, // 6: Validators.GenerateValidatorKey:output_type -> GenerateValidatorKeyResponse
	4, // 7: Validators.ExitValidator:output_type -> ExitValidatorResponse
	6, // 8: Validators.StartValidator:output_type -> StartValidatorResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chainrpc_proto_validators_proto_init() }
func file_chainrpc_proto_validators_proto_init() {
	if File_chainrpc_proto_validators_proto != nil {
		return
	}
	file_chainrpc_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chainrpc_proto_validators_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValidatorsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateValidatorKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitValidatorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitValidatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartValidatorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainrpc_proto_validators_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartValidatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chainrpc_proto_validators_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chainrpc_proto_validators_proto_goTypes,
		DependencyIndexes: file_chainrpc_proto_validators_proto_depIdxs,
		MessageInfos:      file_chainrpc_proto_validators_proto_msgTypes,
	}.Build()
	File_chainrpc_proto_validators_proto = out.File
	file_chainrpc_proto_validators_proto_rawDesc = nil
	file_chainrpc_proto_validators_proto_goTypes = nil
	file_chainrpc_proto_validators_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ValidatorsClient is the client API for Validators service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidatorsClient interface {
	GetValidatorsList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetValidatorsListResponse, error)
	GenerateValidatorKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateValidatorKeyResponse, error)
	ExitValidator(ctx context.Context, in *ExitValidatorInfo, opts ...grpc.CallOption) (*ExitValidatorResponse, error)
	StartValidator(ctx context.Context, in *StartValidatorInfo, opts ...grpc.CallOption) (*StartValidatorResponse, error)
}

type validatorsClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorsClient(cc grpc.ClientConnInterface) ValidatorsClient {
	return &validatorsClient{cc}
}

func (c *validatorsClient) GetValidatorsList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetValidatorsListResponse, error) {
	out := new(GetValidatorsListResponse)
	err := c.cc.Invoke(ctx, "/Validators/GetValidatorsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorsClient) GenerateValidatorKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateValidatorKeyResponse, error) {
	out := new(GenerateValidatorKeyResponse)
	err := c.cc.Invoke(ctx, "/Validators/GenerateValidatorKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorsClient) ExitValidator(ctx context.Context, in *ExitValidatorInfo, opts ...grpc.CallOption) (*ExitValidatorResponse, error) {
	out := new(ExitValidatorResponse)
	err := c.cc.Invoke(ctx, "/Validators/ExitValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorsClient) StartValidator(ctx context.Context, in *StartValidatorInfo, opts ...grpc.CallOption) (*StartValidatorResponse, error) {
	out := new(StartValidatorResponse)
	err := c.cc.Invoke(ctx, "/Validators/StartValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorsServer is the server API for Validators service.
type ValidatorsServer interface {
	GetValidatorsList(context.Context, *Empty) (*GetValidatorsListResponse, error)
	GenerateValidatorKey(context.Context, *Empty) (*GenerateValidatorKeyResponse, error)
	ExitValidator(context.Context, *ExitValidatorInfo) (*ExitValidatorResponse, error)
	StartValidator(context.Context, *StartValidatorInfo) (*StartValidatorResponse, error)
}

// UnimplementedValidatorsServer can be embedded to have forward compatible implementations.
type UnimplementedValidatorsServer struct {
}

func (*UnimplementedValidatorsServer) GetValidatorsList(context.Context, *Empty) (*GetValidatorsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorsList not implemented")
}
func (*UnimplementedValidatorsServer) GenerateValidatorKey(context.Context, *Empty) (*GenerateValidatorKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateValidatorKey not implemented")
}
func (*UnimplementedValidatorsServer) ExitValidator(context.Context, *ExitValidatorInfo) (*ExitValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExitValidator not implemented")
}
func (*UnimplementedValidatorsServer) StartValidator(context.Context, *StartValidatorInfo) (*StartValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartValidator not implemented")
}

func RegisterValidatorsServer(s *grpc.Server, srv ValidatorsServer) {
	s.RegisterService(&_Validators_serviceDesc, srv)
}

func _Validators_GetValidatorsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).GetValidatorsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/GetValidatorsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).GetValidatorsList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validators_GenerateValidatorKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).GenerateValidatorKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/GenerateValidatorKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).GenerateValidatorKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validators_ExitValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitValidatorInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).ExitValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/ExitValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).ExitValidator(ctx, req.(*ExitValidatorInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validators_StartValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartValidatorInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).StartValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/StartValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).StartValidator(ctx, req.(*StartValidatorInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Validators_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Validators",
	HandlerType: (*ValidatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValidatorsList",
			Handler:    _Validators_GetValidatorsList_Handler,
		},
		{
			MethodName: "GenerateValidatorKey",
			Handler:    _Validators_GenerateValidatorKey_Handler,
		},
		{
			MethodName: "ExitValidator",
			Handler:    _Validators_ExitValidator_Handler,
		},
		{
			MethodName: "StartValidator",
			Handler:    _Validators_StartValidator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainrpc/proto/validators.proto",
}
