name: Build and Test
on: [push]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2  
      with:
        go-version: 1.13
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-    

    - name: Install Deps
      run: sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev
      
    - name: Run Test
      run: |
        go test -coverprofile=coverage.txt -covermode=atomic ./...
        bash <(curl -s https://codecov.io/bash)

    - name: Build Ogen
      run: ./scripts/build.sh
        
            
        
                                      
