name: Build and Test
on: [push]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2  
      with:
        go-version: 1.15
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-    
      
    - name: Run Test
      run: |
        go test -coverprofile=coverage.txt -covermode=atomic ./...
        bash <(curl -s https://codecov.io/bash)

    - name: Build Ogen
      uses: crazy-max/ghaction-xgo@v1
      with:
        xgo_version: latest
        go_version: 1.15.x
        dest: build
        pkg: cmd/ogen
        prefix: ogen
        targets: windowsa/amd64,darwin/amd64,linux/arm64,linux/amd64
        race: false
        buildmode: default      
            
        
                                      
