name: Build Docker Images

on: [push]

jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./scripts/full-node/Dockerfile
          public: true  
          push: true
          tags: |
            ghcr.io/olympus-protocol/ogen-full-node:latest
            
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./scripts/validator/Dockerfile
          public: true  
          push: true
          tags: |
            ghcr.io/olympus-protocol/ogen-validator:latest 
            
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./scripts/indexer/Dockerfile
          public: true  
          push: true
          tags: |
            ghcr.io/olympus-protocol/ogen-indexer:latest 
